#! /usr/bin/env bash

ENV_FILE=".env"
VIRTUAL_ENV="venv"
REQUIREMENTS_FILE="requirements.txt"
OPENAI_KEY_VAR_NAME="OPENAI_KEY"
PROGRAM_NAME="chatgpt.py"

cd "$(dirname "$0")"
if [[ ! -d "${VIRTUAL_ENV}" ]] ; then
    echo "Creating virtual environment..."
    python3.11 -m venv "${VIRTUAL_ENV}"
    source venv/bin/activate

    echo "Upgrade pip"
    pip install --upgrade pip

    echo "Installing dependencies..."
    pip3 install --requirement "${REQUIREMENTS_FILE}" > /dev/null
else
    source venv/bin/activate
fi


if [[ ! -e "${ENV_FILE}" ]] ; then
    echo "Creating ${ENV_FILE} file..."
    echo -en "\tOpenAI API key: "
    read OPENAI_KEY
    echo

    echo -en "${OPENAI_KEY_VAR_NAME}='${OPENAI_KEY}'" > "${ENV_FILE}"
fi

python "${PROGRAM_NAME}" ${@}
